### ISSUE TITLE
Drag and Drop Doesn't Allow Items to be Moved once Placed, Results Always Zero

### ISSUE THREAD

**Issue by mrjarbenne** [tunapanda/h5p-standalone#15] opened 2017-12-18 03:17 UTC
You can test this using the Drag and Drop example on h5p.org: https://h5p.org/drag-and-drop#example=63159

Once one of the labels has been clicked on and placed, it can no longer be moved and appears somewhat translucent (the appearance it is in while being dragged), rather than reverting back to solid once released as is the case on .org. 

Because of this, the labels are not recognized as being in the correct placement, and the results are always zero.

![2017-12-17_22-15-00](https://user-images.githubusercontent.com/480667/34088531-eefe4b28-e377-11e7-9513-6014dbbbfd0b.gif)

**Comment by Jakeii** [comment] 2018-01-11 14:30
Very strange, probably an issue with dependencies, anything in the console?

**Comment by mrjarbenne** [comment] 2018-01-17 21:22
There are these two errors in the console: 

![2018-01-17_16-21-06](https://user-images.githubusercontent.com/480667/35067609-7925f052-fba2-11e7-9f6a-13841dc5f6ac.png)

Please let me know if I can assist further.

**Comment by Jakeii** [comment] 2018-01-17 22:56
Thanks, I fixed a dependency issue that I thought could be the cause, but it still isn't working when I tested. I'll investigate further when I have a moment.

**Comment by shippeli** [comment] 2018-03-15 13:46
Hi, i got the same error:

h5p-drag-question.js:1 Uncaught TypeError: Cannot set property 'originalPosition' of undefined
    at Z.fn.init.revert (https://................../H5P.DragQuestion-1.11/h5p-drag-question.js:1:36338)
    ......

**Comment by Jakeii** [comment] 2018-03-24 17:29
Hi @mrjarbenne and @shippeli this has been fixed as of 1.2.0, turns out newer versions of the DragQuestion h5p had a breaking change that required a higher version of jQuery.

**Closed by Jakeii** 2018-03-24 17:29 UTC
Labels: bug

**Comment by shippeli** [comment] 2018-06-05 10:01
Hi,for me the problem still exists in 1.3.4
